.default_rules:
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
    - if: ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
    - if: ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev")

stages:
  - test

test:
  stage: test
  image: python:3.10
  script:
    - cd backend
    - pip install pipenv
    - pipenv install
    - python manage.py makemigrations
    - python manage.py migrate
    - pipenv shell
    - python manage.py test

test:
  stage: test
  image: node:latest
  script:
    - cd frontend
    #- npm install
    - npm test -a

